---
- name: update system
  portage:
    sync: yes

- name: create symlink
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: /usr/local/development, dest: /root/development }
    - { src: /usr/local/development/xentoo/profiles/amd64, dest: /etc/portage/make.profile }

- name: create make conf
  template:
    src: etc/portage/make.conf.j2
    dest: /etc/portage/make.conf
    owner: root
    group: root
    mode: 0644

- name: create directories
  file:
    dest: /etc/portage/repos.conf
    owner: root
    group: root
    mode: 0755
    state: directory

- name: create repos conf
  template:
    src: etc/portage/repos.conf/xentoo.conf.j2
    dest: /etc/portage/repos.conf/xentoo.conf
    owner: root
    group: root
    mode: 0644

- name: update toolchain
  portage:
    update: yes
    newuse: yes
    deep: yes
    package: '@world'
    quiet: yes
    jobs: 3
