---
- name: create xentoo directories
  file:
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - { dest: /var/lib/xentoo }

    - { dest: /var/lib/xentoo/conf }
    - { dest: /var/lib/xentoo/conf/etc }
    - { dest: /var/lib/xentoo/conf/etc/portage }
    - { dest: /var/lib/xentoo/conf/etc/portage/repos.conf }

    - { dest: /var/lib/xentoo/rootfs }
    - { dest: /var/lib/xentoo/rootfs/lib64 }
    - { dest: /var/lib/xentoo/rootfs/usr }
    - { dest: /var/lib/xentoo/rootfs/usr/lib64 }

    - { dest: /var/lib/xentoo/distfiles }
    - { dest: /var/lib/xentoo/packages }
    - { dest: /var/lib/xentoo/deploy }
    - { dest: /var/lib/xentoo/overlays }

- name: create portage config
  template:
    src: etc/portage/make.conf.j2
    dest: /var/lib/xentoo/conf/etc/portage/make.conf
    owner: root
    group: root
    mode: 0644

- name: create bash profile
  template:
    src: root/.bash_profile.j2
    dest: /root/.bash_profile
    owner: root
    group: root
    mode: 0644

- name: create profile symlink
  file:
    src: /var/lib/xentoo/overlays/xentoo/profiles/amd64
    dest: /var/lib/xentoo/conf/etc/portage/make.profile
    state: link

- name: create repos conf
  template:
    src: etc/portage/repos.conf/xentoo.conf.j2
    dest: /var/lib/xentoo/conf/etc/portage/repos.conf/xentoo.conf
    owner: root
    group: root
    mode: 0644

- name: create xentoo symlinks
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    force: yes
    state: link
  with_items:
    - { src: lib64, dest: /var/lib/xentoo/rootfs/lib }
    - { src: lib64, dest: /var/lib/xentoo/rootfs/usr/lib }
    - { src: /usr/local/development/xentoo, dest: /var/lib/xentoo/overlays/xentoo }
